### ISSUE TITLE
Player Character Todo List

### ISSUE THREAD

**Issue by CyxFTS** [shen92/Hope-Island-Unity#49]
- [ ] 1. Better Shading
- [ ] 2. Skill Upgrade System
- [ ] 3. Slash Effect for melee attack and hit
- [ ] 4. Sound Effect
- [ ] 5. Data Binding with UI
